"""
YOLOv8 Training Script for Road Defect Detection
Trains YOLOv8n model on RDD2022 dataset
"""

import os
from ultralytics import YOLO
import yaml


def create_dataset_yaml():
    """Create dataset configuration file for YOLO"""
    dataset_config = {
        'path': '../data',  # Dataset root directory
        'train': 'images/train',
        'val': 'images/val',
        'test': 'images/test',

        # Class names
        'names': {
            0: 'pothole',
            1: 'longitudinal_crack',
            2: 'transverse_crack',
            3: 'alligator_crack'
        }
    }

    with open('data/dataset.yaml', 'w') as f:
        yaml.dump(dataset_config, f)

    print("✓ Dataset config created: data/dataset.yaml")
    return 'data/dataset.yaml'


def train_model(epochs=50, img_size=640, batch_size=16):
    """
    Train YOLOv8n model for road defect detection

    Args:
        epochs: Number of training epochs
        img_size: Image size for training
        batch_size: Batch size
    """
    print("=" * 60)
    print("RoadDoctor ML - Training YOLOv8n")
    print("=" * 60)

    # Create dataset config
    dataset_yaml = create_dataset_yaml()

    # Load pretrained YOLOv8n model
    model = YOLO('yolov8n.pt')
    print("✓ Loaded pretrained YOLOv8n model")

    # Train the model
    print(f"\nStarting training for {epochs} epochs...")
    results = model.train(
        data=dataset_yaml,
        epochs=epochs,
        imgsz=img_size,
        batch=batch_size,
        device='cpu',  # Use 'cuda' if GPU available
        project='runs/train',
        name='road_defect_detector',

        # Augmentation settings
        augment=True,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=10.0,
        translate=0.1,
        scale=0.5,
        fliplr=0.5,
        mosaic=1.0,

        # Training settings
        patience=20,
        save=True,
        plots=True,
        verbose=True
    )

    # Save best model
    best_model_path = 'runs/train/road_defect_detector/weights/best.pt'
    if os.path.exists(best_model_path):
        os.makedirs('models', exist_ok=True)
        os.system(f'cp {best_model_path} models/best.pt')
        print(f"\n✓ Best model saved to: models/best.pt")

    # Print results
    print("\n" + "=" * 60)
    print("Training Complete!")
    print("=" * 60)
    print(f"Results saved to: runs/train/road_defect_detector")

    return results


def evaluate_model(model_path='models/best.pt'):
    """Evaluate trained model"""
    model = YOLO(model_path)

    # Validate the model
    metrics = model.val()

    print("\n" + "=" * 60)
    print("Model Performance Metrics:")
    print("=" * 60)
    print(f"mAP50: {metrics.box.map50:.3f}")
    print(f"mAP50-95: {metrics.box.map:.3f}")
    print(f"Precision: {metrics.box.mp:.3f}")
    print(f"Recall: {metrics.box.mr:.3f}")

    return metrics


if __name__ == "__main__":
    # Note: This script requires RDD2022 dataset to be downloaded
    # For hackathon demo, you can use a small subset or mock data

    print("\n📋 RDD2022 Dataset Setup Required:")
    print("1. Download RDD2022 from: https://github.com/sekilab/RoadDamageDetector")
    print("2. Place images in: data/images/train, data/images/val")
    print("3. Place labels in: data/labels/train, data/labels/val")
    print("\nFor quick demo, you can use mock data generated by data_generator.py\n")

    # Uncomment to run training:
    # train_model(epochs=50, img_size=640, batch_size=16)
    # evaluate_model()
